baseURL = "https://blog.duetopia.com/"
languageCode = "zh-cn"
title = "Duetopia Blog"
theme = "PaperMod"

[params]
  env = "production"
  title = "Duetopia Blog"
  description = "duet 的个人博客"
  author = "duet"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  defaultTheme = "auto"
  favicon = "/favicon.png"

  [params.profileMode]
    enabled = true
    title = "duet"
    subtitle = "记录想法，分享生活"
    imageUrl = "/avatar.png"
    imageTitle = "duet"
    imageWidth = 120
    imageHeight = 120

[menu]
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2
