baseURL = "https://blog.duetopia.com/"
languageCode = "zh-cn"
title = "Duet"
theme = "PaperMod"

[params]
  env = "production"
  title = "Duet"
  description = "duet 的个人博客"
  author = "duet"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  defaultTheme = "auto"
  favicon = "/favicon.png"

  [params.label]
    text = "Duet"
    icon = "/avatar.png"
    iconHeight = 30

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/Duetopid"


[menu]
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2
